name: Commit and Push

on:
  workflow_dispatch:

jobs:
  commit_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Git configuration
        run: |
          git config --local user.email "36035885+x-color@users.noreply.github.com"
          git config --local user.name "x-color"
      - run: echo "$(date)" >> testfile.txt
      - name: 1st Commit
        run: |
          git add testfile.txt
          git diff --cached --quiet || git commit -m "Update testfile\n\nUpdated at $(date) by GitHub Actions"
      - run: echo "$(date)" >> testfile.txt
      - name: 2nd Commit
        run: |
          git add testfile.txt
          git diff --cached --quiet || git commit -m "Update testfile\n\nUpdated at $(date) by GitHub Actions"
      - name: Push changes
        run: |
          if [[ `git rev-parse HEAD` == `git rev-parse origin/master` ]]; then
            git push origin main
          fi
