name: Go
on:
  push:
    # paths:
    #  - '**.go'
    tags-ignore:
      - 'v*.*.*'
    # branches:
    #   - '*'

jobs:
  checkout:
    name: Checkout
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
