name: Go
on:
  push:
    paths:
      - '**.go'
    branches-ignore:
      - 'test'

jobs:
  checkout:
    name: Checkout
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
