name: notify

on:
  push:
    branches:
      - notify-slack

jobs:
  notify:
    runs-on: ubuntu-18.04
    steps:
    - name: exec
      run: | 
        echo 'execute!!'

    - name: Slack Notification Success
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: pullreminders/slack-action@master
      with:
        args: '{\"channel\":\"CQSASTL14\",\"text\":\"Hello world\"}'