name: notify

on:
  push:
    branches:
      - notify-slack

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - name: exec
      run: echo 'execute!!'

    - name: Slack Notification
      if: success()
      uses: rtCamp/action-slack-notify@v2.0.0
      env:
        SLACK_CHANNEL: channel_name
        SLACK_ICON: https://github.com/x-color/try-github-actions/blob/notify-slack/resources/icon.png
        SLACK_MESSAGE: 'Success :rocket:'
        SLACK_TITLE: Success GitHub Actions
        SLACK_USERNAME: Sheeeep
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}