name: notify

on:
  push:
    branches:
      - notify-slack

jobs:
  notify:
    runs-on: ubuntu-18.04
    steps:
    - name: exec
      run: | 
        echo 'execute!!'

    - name: Slack Notification Success
      uses: rtCamp/action-slack-notify@v2.0.0
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_COLOR: '#5cb85c'
        SLACK_TITLE: 'Success to Deploy to GitHub Pages :rocket:'
        SLACK_MESSAGE: ':closed_book: ${{ github.repository }}'